### ISSUE TITLE
Error in the step of functional connectivity analysis

### ISSUE THREAD

**Issue by rickwith** [realmsong504/pDOC#4]
Dear Dr. Song,

  I got an error message in the step of fc analysis with pDOC toolbox, here are the detailed log information as follows, i am very appreciate if you can spare some time to find what is exactly wrong.

_Processing 1 sub001
Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.Cannot read header extension.copy standard brain network atlas.
Warning: spm.util.cdir was DEPRECATED in SPM8 and has now been REMOVED.
Please update your batches to use BasicIO instead. 
Conversion Normalise:EstWrite -> Old Normalise:EstWrite
You might have to manually update the template image in Old Normalise:EstWrite.
Conversion Normalise:Write -> Old Normalise:Write
Item oldnorm: No field(s) named
estwrite

------------------------------------------------------------------------
Running job #1
------------------------------------------------------------------------
Running 'Change Directory (Deprecated)'
New working directory: H:\data\sub001\fMRI
Done    'Change Directory (Deprecated)'
Running 'Slice Timing'

SPM12: spm_slice_timing (v6130)                    00:11:45 - 30/04/2020
========================================================================
Number of slices is...                  :                             28
Time to Repeat (TR) is...               :                              2
Parameters are specified as...          :                  slice indices
Completed                               :          00:12:06 - 30/04/2020
Done    'Slice Timing'
Running 'Realign: Estimate & Reslice'

SPM12: spm_realign (v7141)                         00:12:06 - 30/04/2020
========================================================================
Completed                               :          00:12:56 - 30/04/2020

SPM12: spm_reslice (v7141)                         00:12:56 - 30/04/2020
========================================================================
Completed                               :          00:13:19 - 30/04/2020
Done    'Realign: Estimate & Reslice'
Running 'Old Normalise: Estimate & Write'
Smoothing by 0 & 8mm..
Coarse Affine Registration..
Fine Affine Registration..
3D CT Norm...
 iteration  1:  FWHM =  9.037 Var = 5.11102
 iteration  2:  FWHM =  8.008 Var = 1.61743
 iteration  3:  FWHM =  7.559 Var = 1.4599
 iteration  4:  FWHM =  7.476 Var = 1.4189
 iteration  5:  FWHM =  7.459 Var = 1.41071
 iteration  6:  FWHM =  7.445 Var = 1.40765
 iteration  7:  FWHM =  7.444 Var = 1.40756
 iteration  8:  FWHM =  7.442 Var = 1.40756
 iteration  9:  FWHM =  7.442 Var = 1.40755
 iteration 10:  FWHM =  7.441 Var = 1.40755
 iteration 11:  FWHM =  7.443 Var = 1.40755
 iteration 12:  FWHM =  7.443 Var = 1.40755
 iteration 13:  FWHM =  7.442 Var = 1.40755
 iteration 14:  FWHM =  7.443 Var = 1.40755
 iteration 15:  FWHM =  7.444 Var = 1.40755
 iteration 16:  FWHM =  7.443 Var = 1.40755
Saving Parameters..

SPM12: spm_write_sn (v4878)                        00:13:30 - 30/04/2020
========================================================================
Completed                               :          00:13:30 - 30/04/2020
Done    'Old Normalise: Estimate & Write'
Running 'Old Normalise: Write'

SPM12: spm_write_sn (v4878)                        00:13:30 - 30/04/2020
========================================================================
Completed                               :          00:13:32 - 30/04/2020
Done    'Old Normalise: Write'
Running 'Smooth'
Done    'Smooth'
Running 'Coregister: Estimate & Reslice'

SPM12: spm_coreg (v6435)                           00:13:50 - 30/04/2020
========================================================================
Completed                               :          00:14:31 - 30/04/2020

SPM12: spm_reslice (v7141)                         00:14:31 - 30/04/2020
========================================================================
Completed                               :          00:14:31 - 30/04/2020
Done    'Coregister: Estimate & Reslice'
Done

intersection between mask & brain: 0.745
removing the head motion and whole brain mean.
read the 3D files and form a 4D matrix 
multiple regression 
rewrite the new 3D files 
band pass filtering...
	Using the brain mask. 
	reading fMRI time series. 
	filter parameter:  
		TR=2 sec. 
		Low_cutoff=0.01 Hz. 
		High_cutoff=0.08 Hz. 
	filter...
	saving the result... 
	Bandpass filtering finished. 

------------------------------------------------------------------------
Running job #1
------------------------------------------------------------------------
Running 'Change Directory (Deprecated)'
New working directory: H:\data\sub001\fMRI\afni
Done    'Change Directory (Deprecated)'
Running '3D to 4D File Conversion'
Done    '3D to 4D File Conversion'
Done

 Functional connectivity analysis.

 computing sub001_DMN ...

	 ROI: H:\data\sub001\fMRI\EPI\brain_ROI_DOC\DMN\w01_aMPFC.nii  ...
	number of voxels in ROI = 7

	 ROI: H:\data\sub001\fMRI\EPI\brain_ROI_DOC\DMN\w02_PCC.nii    ...
	number of voxels in ROI = 8

	 ROI: H:\data\sub001\fMRI\EPI\brain_ROI_DOC\DMN\w03_L.LatP.nii ...
	number of voxels in ROI = 8

	 ROI: H:\data\sub001\fMRI\EPI\brain_ROI_DOC\DMN\w04_R.LatP.nii ...
	number of voxels in ROI = 9

 computing sub001_ExecuContr ...

	 ROI: H:\data\sub001\fMRI\EPI\brain_ROI_DOC\ExecuContr\w01_DMPFC.nii      ...
	number of voxels in ROI = 6

	 ROI: H:\data\sub001\fMRI\EPI\brain_ROI_DOC\ExecuContr\w02_L.PFC.nii      ...
	number of voxels in ROI = 9

	 ROI: H:\data\sub001\fMRI\EPI\brain_ROI_DOC\ExecuContr\w03_R.PFC.nii      ...
	number of voxels in ROI = 7

	 ROI: H:\data\sub001\fMRI\EPI\brain_ROI_DOC\ExecuContr\w04_L.Parietal.nii ...
	number of voxels in ROI = 7

	 ROI: H:\data\sub001\fMRI\EPI\brain_ROI_DOC\ExecuContr\w05_R.Parietal.nii ...
	number of voxels in ROI = 6

 computing sub001_Salience ...

	 ROI: H:\data\sub001\fMRI\EPI\brain_ROI_DOC\Salience\w01_L.AIns.nii ...
	number of voxels in ROI = 5

	 ROI: H:\data\sub001\fMRI\EPI\brain_ROI_DOC\Salience\w02_R.AIns.nii ...
	number of voxels in ROI = 6

	 ROI: H:\data\sub001\fMRI\EPI\brain_ROI_DOC\Salience\w03_dACC.nii   ...
	number of voxels in ROI = 9

 computing sub001_Sensorimotor ...

	 ROI: H:\data\sub001\fMRI\EPI\brain_ROI_DOC\Sensorimotor\w01_L.M1.nii ...
	number of voxels in ROI = 9

	 ROI: H:\data\sub001\fMRI\EPI\brain_ROI_DOC\Sensorimotor\w02_R.M1.nii ...
	number of voxels in ROI = 7

	 ROI: H:\data\sub001\fMRI\EPI\brain_ROI_DOC\Sensorimotor\w03_SMA.nii  ...
	number of voxels in ROI = 8

 computing sub001_Auditory ...

	 ROI: H:\data\sub001\fMRI\EPI\brain_ROI_DOC\Auditory\w01_L.A1.nii ...
	number of voxels in ROI = 6

	 ROI: H:\data\sub001\fMRI\EPI\brain_ROI_DOC\Auditory\w02_R.A1.nii ...
	number of voxels in ROI = 5

	 ROI: H:\data\sub001\fMRI\EPI\brain_ROI_DOC\Auditory\w03_MCC.nii  ...
	number of voxels in ROI = 5

 computing sub001_Visual ...

	 ROI: H:\data\sub001\fMRI\EPI\brain_ROI_DOC\Visual\w01_L.V1.nii ...
	number of voxels in ROI = 7

	 ROI: H:\data\sub001\fMRI\EPI\brain_ROI_DOC\Visual\w02_R.V1.nii ...
	number of voxels in ROI = 9

	 ROI: H:\data\sub001\fMRI\EPI\brain_ROI_DOC\Visual\w03_L.V4.nii ...
	number of voxels in ROI = 6

	 ROI: H:\data\sub001\fMRI\EPI\brain_ROI_DOC\Visual\w04_R.V4.nii ...
	number of voxels in ROI = 8
Index exceeds matrix dimensions.

Error in f_data_quality_evaluation (line 187)
    axial_slice_vals = compound_RGB(:,:,axial_slice_number,:);

Error in f_DOC_prognosication_rsfMRI_clinical (line 46)
f_data_quality_evaluation(subject_list_file);

Error in pDOC>pb_calculation_Callback (line 196)
    f_DOC_prognosication_rsfMRI_clinical(patient_directory,...

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in pDOC (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)pDOC('pb_calculation_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback_

**Comment by realmsong504** [comment]
Hi, richwith, If your file extension is .nii, make sure it's in the correct NIFTI version. To make sure they are generated correctly, you can convert from your DICOM using "dcm2niigui". You can find  "dcm2niigui" in the toolbox mricron (http://www.cabiatl.com/mricro/mricron/dcm2nii.html).

**Comment by rickwith** [comment]
> Hi, richwith, If your file extension is .nii, make sure it's in the correct NIFTI version. To make sure they are generated correctly, you can convert from your DICOM using "dcm2niigui". You can find "dcm2niigui" in the toolbox mricron (http://www.cabiatl.com/mricro/mricron/dcm2nii.html).

Actually i have used the dcm2niigui.exe in the mricron program for the data conversion. Is there other reason that casue such situation?

**Comment by realmsong504** [comment]
I am not sure whether there are other reason. Can you send two or three nii files to me? If you like, i can help to check them. My email address is msong@nlpr.ia.ac.cn.
